config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true,
        length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:create]

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'What is Quarantalk?';
        @content = 'Quarantalk makes exercising in times of social distancing more interesting! Talk to new people with similar interests when out for a walk.';
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:show, :index]
        
    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.new(post_params)

        if (@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if (@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="card card-body bg-light">
        <p><strong><%= comment.username %></strong>: <%= comment.body %>
        <%= link_to '[X]', [comment.post, comment],
            method: :delete,
            data: { confirm: 'Are you sure?' } %></p>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |frm| %>
    <p>
        <%= frm.label :username %><br>
        <%= frm.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= frm.label :body %><br>
        <%= frm.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= frm.submit({:class => 'btn btn-default'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quarantalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="">Quarantalk</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", home_path %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Post", new_post_path %>
      </li>
    </ul>
    <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    -->
  </div>

  <p class="navbar-text float-right" style="margin: 0px">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

</nav>

<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |frm| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= frm.label :title %><br>
        <%= frm.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= frm.label :body %><br>
        <%= frm.text_area(:body, {:class => 'form_control'})%>
    </p>
    <p>
        <%= frm.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Posts near you</h1>
<% @posts.each do |post| %>
    <div class="card card-body bg-light">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to "Read More", post_path(post), :class => 'btn btn-dark' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |frm| %>
    <p>
        <%= frm.label :title %><br>
        <%= frm.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= frm.label :body %><br>
        <%= frm.text_area(:body, {:class => 'form_control'})%>
    </p>
    <p>
        <%= frm.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post),
                method: :delete,
                data: {confirm: 'Are you sure?'},
                :class => 'btn btn-default' %>

<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>